export const DarkMode = (Darkmode: boolean) => {
  const r: any = document.querySelector(":root");
  if (Darkmode) {
    localStorage.setItem("DarkMode", "1");
    r.style.setProperty("--nav-icons", "#ffffffee");
    r.style.setProperty("--scrollbar-bg", "#0b0d38");
    r.style.setProperty("--scrollbar-thumb", "#13175f");
    r.style.setProperty("--main-color", "#b439ff");
    r.style.setProperty("--bg-color", "#07071c");
    r.style.setProperty("--nav-bg-color", "#0c0c2e");
    r.style.setProperty("--nav-border-color", "#141450");
    r.style.setProperty("--input-bg-color", "#101040");
    r.style.setProperty("--text-title-color", "#efefef");
    r.style.setProperty("--text-color", "#e8e8e8d9");
    r.style.setProperty("--button-bg-color", "#14144a");
    r.style.setProperty("--button-bg-color-hover", "#191961");
    r.style.setProperty("--chat-bg-color", "#0d0d33");
    r.style.setProperty("--chat-message-bg-color", "#07071c");
    r.style.setProperty("--post-time-color", "#07071c");
    r.style.setProperty("--profile-info-color", "#d9d9d9");
    r.style.setProperty("--line-color", "#111146");
    r.style.setProperty("--green", "#00f47f");
    r.style.setProperty("--orange", "#f97b22");
    r.style.setProperty("--blue", "#19a7ce");
    r.style.setProperty("--react-color", "#ececec");
    r.style.setProperty("--block-bg", "#090b2e");
    r.style.setProperty("--block-button-bg", "#12124a");
    r.style.setProperty("--block-button-bg-hover", "#1d1d74");
    r.style.setProperty("--block-button-text", "#383838");
    r.style.setProperty("--chat-send-bg", "#0d1042");
    r.style.setProperty("--chat-send-border", "#161a6b");
    r.style.setProperty("--message-time", "#ffffff");
    r.style.setProperty("--message-time-bg", "#131761");
    r.style.setProperty("--my-message", "#ffffff");
    r.style.setProperty("--chat-input-bg", "#161a6b");
    r.style.setProperty("--chat-input-stroke", "#181d7b");
    r.style.setProperty("--input-color", "#ffffff");
  } else {
    localStorage.setItem("DarkMode", "0");

    r.style.setProperty("--nav-icons", "#b4b4b4");
    r.style.setProperty("--scrollbar-bg", "#dadada");
    r.style.setProperty("--scrollbar-thumb", "#c5c5c5");
    r.style.setProperty("--main-color", "#b439ff");
    r.style.setProperty("--bg-color", "#f6f6f6");
    r.style.setProperty("--nav-bg-color", "#ffffff");
    r.style.setProperty("--nav-border-color", "#dddddd");
    r.style.setProperty("--input-bg-color", "#ececec");
    r.style.setProperty("--text-title-color", "#323232");
    r.style.setProperty("--text-color", "#000000d9");
    r.style.setProperty("--button-bg-color", "#f5f5f5");
    r.style.setProperty("--button-bg-color-hover", "#e9e9e9");
    r.style.setProperty("--chat-bg-color", "#eaeaea");
    r.style.setProperty("--chat-message-bg-color", "#f5f5f5");
    r.style.setProperty("--post-time-color", "#a6a6a6");
    r.style.setProperty("--profile-info-color", "#d9d9d9");
    r.style.setProperty("--line-color", "#eaeaea");
    r.style.setProperty("--block-button-bg", "#efefef");
    r.style.setProperty("--block-button-bg-hover", "#e9e9e9");
    r.style.setProperty("--block-button-text", "#383838");
    r.style.setProperty("--green", "#00f47f");
    r.style.setProperty("--orange", "#f97b22");
    r.style.setProperty("--blue", "#19a7ce");
    r.style.setProperty("--react-color", "#aaaaaa");
    r.style.setProperty("--block-bg", "#f7f7f7");
    r.style.setProperty("--chat-send-bg", "#f1f1f1");
    r.style.setProperty("--chat-send-border", "#d3d3d3");
    r.style.setProperty("--message-time", "#ffffff");
    r.style.setProperty("--message-time-bg", "#414141");
    r.style.setProperty("--my-message", "#ffffff");
    r.style.setProperty("--chat-input-bg", "#ebebeb");
    r.style.setProperty("--chat-input-stroke", "#dedede");
    r.style.setProperty("--input-color", "#000000");
  }
};
